fix(schema): Introduce BinarySign struct to fix schema bug (#6058)
This PR fixes the bug discussed in
[discussion#6057](https://github.com/orgs/goreleaser/discussions/6057).

The schema & schema-pro incorrectly return 9 valid options for
`binary_signs` -> `artifacts` instead of two supported: `none | binary`.
As a result, language servers report 9 valid options, and `gorelease
check` succeeeds but actual signing fails.
Language server incorrect values:
<img width="206" height="293" alt="Screenshot 2025-09-08 at 16 40 44"
src="https://github.com/user-attachments/assets/de4e5511-36a4-4323-a350-0851bb8858c3"
/>

check passes, signing fails:
```
$ goreleaser check
  • checking                                  path=.goreleaser.yaml
  • 1 configuration file(s) validated
  • thanks for using GoReleaser!
...
  • signing binaries
invalid list of artifacts to sign: all
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.12.0/x64/goreleaser' failed with exit code 1
```


If applied, this commit will introduce `BinarySign` to resolve the bug
in the schema, to align with the documentation & actual behaviour of the
code.

tests updated in `internal/pipe/sign/sign_binary_test.go` and a small
`toSign` wrapper to ensure backwards compatibility with existing
`sign()`.

Build succeeds locally:
```
go build -o goreleaser .  
➜  goreleaser git:(fix/binary_sign) ./goreleaser --version
  ____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Release engineering, simplified.
https://goreleaser.com

GitVersion:    v2.12.1-0.20250908073636-c8b464ad5be4
GitCommit:     c8b464ad5be4972e5daec0678cef317e6a89de01
GitTreeState:  clean
BuildDate:     2025-09-08T07:36:36
BuiltBy:       unknown
GoVersion:     go1.25.1
Compiler:      gc
ModuleSum:     unknown
Platform:      darwin/arm64
```

`task ci` fails due to what seems like an unrelated error? 
```
--- FAIL: TestBuild (1.17s)
    build_test.go:123:
        	Error Trace:	./goreleaser/internal/builders/poetry/build_test.go:123
        	Error:      	Received unexpected error:
        	            	chtimes: dist/proj-all-all/--py3-none-any.whl: chtimes dist/proj-all-all/--py3-none-any.whl: no such file or directory
        	Test:       	TestBuild
FAIL
```

---------

Signed-off-by: Frenchie <frenchie@ensignia.co>
Co-authored-by: Carlos Alexandro Becker <caarlos0@users.noreply.github.com>