ci: update golangci-lint to v1.62 (#5288)
This PR updates the version of golangci-lint to the latest
[v1.62](https://github.com/golangci/golangci-lint/releases/tag/v1.62.0)
and fixes appeared lint issues:

```
❯ golangci-lint run
internal/archivefiles/archivefiles.go:144:2: redefines-builtin-id: redefinition of the built-in function min (revive)
        var min int
        ^
internal/archivefiles/archivefiles.go:146:3: redefines-builtin-id: redefinition of the built-in function min (revive)
                min = len(b)
                ^
internal/archivefiles/archivefiles.go:148:3: redefines-builtin-id: redefinition of the built-in function min (revive)
                min = len(a)
                ^
cmd/root.go:152:29: redefines-builtin-id: redefinition of the built-in type rune (revive)
func timedRunE(verb string, rune func(cmd *cobra.Command, args []string) error) func(cmd *cobra.Command, args []string) error {
                            ^
internal/git/config_test.go:39:2: contains: use require.Contains (testifylint)
        require.True(t, strings.Contains(gitCfg, "branch.relative_branch.remote=."))
        ^
```